version: 0.2

phases:
  install:
    runtime.versions:
      nodejs: 20.12.2

    commands:
      - echo install started on `date`
      - npm install

  build:
    commands:
      - npm run build
      - echo Build completed successfully pear

artifacts:
  files:
    - "**/*"
