version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX
      - echo Build completed successfully

artifacts:
  files:
    - "**/*"
